export const DIETS_REQUEST = 'DIETS_REQUEST';
export const DIETS_SUCCESS = 'DIETS_SUCCESS';
export const DIETS_FAILURE = 'DIETS_FAILURE';

export const RECIPES_BY_NAME_REQUEST = 'RECIPES_BY_NAME_REQUEST';
export const RECIPES_BY_NAME_SUCCESS = 'RECIPES_BY_NAME_SUCCESS';
export const RECIPES_BY_NAME_FAILURE = 'RECIPES_BY_NAME_FAILURE';

export const RECIPE_BY_ID_REQUEST = 'RECIPE_BY_ID_REQUEST';
export const RECIPE_BY_ID_SUCCESS = 'RECIPE_BY_ID_SUCCESS';
export const FETCH_RECIPE_BY_ID_FAILURE = 'FETCH_RECIPE_BY_ID_FAILURE';

export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';